### PR TITLE
Updated Readme and small change to part

### PR DESCRIPTION
**Pull request by goldfishlaser**
Just added what's new and made a minor change to the part.

### CODE REVIEW

**Comment by maltfield** [comment]
Thanks for the PR :) The changes to the `README.md` and `.scad` file look fine, but I don't know how to check the `.stl` file.

Do you have any advice on how I can diff the `.stl` file and scan/sanitize it for any potentially-malicious changes? Is there something like [qvm-convert](https://blog.invisiblethings.org/2013/02/21/converting-untrusted-pdfs-into-trusted.html) or [Dangerzone](https://dangerzone.rocks/) for `.stl` files?

**Comment by goldfishlaser** [comment]
Have no idea. But it seemed to provide a diff when I submitted it.

**Comment by goldfishlaser** [comment]
Oh sorry, right, the stl not the scad. Yeah, no idea.

**Comment by maltfield** [comment]
The GitHub WUI says the `.stl` file's diffs are:

> 39,614 additions, 39,726 deletions not shown because the diff is too large

I think we need to figure out a safe way to diff this before I can merge it. The `.stl` file is generated *from* the `.scad` file, right? If so, I guess it's redundant and we can omit it? I'll merge this if you exclude the `.stl` file. Otherwise we'll need to figure out some way to scan/sanitize it.

**Pull request closed without merging**
